### ISSUE TITLE
New guideline ES.3 "don't repeat yourself" (was: Add section about duplicated code to P.3: "Express Intent")

### ISSUE THREAD

**Issue by peno2** [isocpp/CppCoreGuidelines#1712]
EDIT: I keep the original proposal here, although the pull request has diverged somewhat after suggestion from the editor.

I suggest that a section about duplicated code is added to P.3 "Express Intent".

Duplicated code is a common source of a number of problems. I suggest to just ad a simple example without digging deeper into all issues related to the subject.

-----
#### Example
Redundant or duplicated code obscures intent and makes it harder to understand the logic. Avoid code duplication.

    void day(bool workday)    // Bad, duplicated code.
    {
        if (workday) {
            breakfast();
            work();
            dinner();   
        }
        else {
            breakfast();
            readABook();
            dinner();
        }
    }

    void day(bool workday)    // Good, no duplicated code.
    {
        breakfast();

        if (workday)
            work();
        else
            readABook();

        dinner();
    }

**Comment by BenBE** [comment]
While I agree on you the issue, I think a better rephrasing is `avoid code duplication`. There are situations where you can't simply "remove" the duplicated code, but where replacing it with something that avoids the source of duplication will help you structure your code better.

Caveat: There are situations where you even want to keep the redundancy. Your example is a borderline case of this.

**Comment by peno2** [comment]
I agree, it sounds better with "avoid code duplication". I will update the original post.

I understand that there are cases where you for some reason want to keep duplication, but then I think that this should be clearly stated and motivated. In the majority of the code duplication that I see as a reviewer of code, there are no good reason for duplicating.

**Comment by BenBE** [comment]
> In the majority of the code duplication that I see as a reviewer of code, there are no good reason for duplicating.

ACK. Keeping duplication is the exception. Usually less code is better: gives less opportunity to make mistakes.

**Comment by MikeGitb** [comment]
I'll say it: I find version 1 easier to read (probably to some part because version 2 is missing the braces). 

My general point: No one disputes the danger of code duplication under maintenence and it should be called out, but avoiding even trivial code duplication at all cost (e.g. by significantly increasing code complexity) isn't necessarily better either. Extreme case are  const/non-const getters.

**Comment by peno2** [comment]
@MikeGitb 
I updated the code example with spaces to make the code more readable.

**Comment by MikeGitb** [comment]
FYI: Personally I still don't think this is necessarily better (maybe because I find it easier to read to linear alternatives than an if/else in the middle of a function. But this is really not something I have a strong opinion on so I'm fine with whatever the maintainers accept.

**Comment by peno2** [comment]
I am open for some better example if anyone has a suggestion. I took the one above, since I think it is a short and simple illustration of the problem at hand. One could think of much more convoluted examples that are closer to what you stumble upon in reality.

Also, it would be easy change the example to not have the if-else in the middle of the function.
Would this be better:

    void day(bool workday)    // Bad, duplicated code.
    {
        if (workday) {
            breakfast();
            work();
        }
        else {
            breakfast();
            readABook();
        }
    }

    void day(bool workday)    // Good, no duplicated code.
    {
        breakfast();

        if (workday)
            work();
        else
            readABook();
}

**Comment by MikeGitb** [comment]
I'd say, leave your PR as it is and if someone has an improvement they can fix it later.

**Comment by xtofl** [comment]
This specific example happens to be a dubious one; a workday may look entirely different than a weekend day (I have no breakfast on a work day, as it happens).  The repetition in this case is rather accidental, and extracting the common part is not intrinsic to the problem domain.  I would argue that in this case, the _intent_ wasn't properly conveyed: providing a template for a day.

```C++
auto day = [](auto action){
  breakfast();
  action();
  supper();
};

day(work);
day(read_a_book);
```

But...

When I _do_ agree that repetition is bad, is when it is intrinsic to the problem.  I often see e.g. the same parameter handling code repeated:

```C++
// BAD: repeating the same pattern over and over
param1 = new Param("A", ipc_connection);
main.add(param1);
param1.request_update();
param1.on_change(function1);

param2 = new Param("B", ipc_connection);
main.add(param2);
param2.request_update();
param2.on_change(function2);

param3 = new Param("C", ipc_connection);
main.add(param3);
param3.request_update();
param3.on_change(function3);
```

```C++
// better: repetition is limited to the essence (parameter names)
auto add_param= [&main, &ipc_connection](auto name){
  auto param = new Param(name, ipc_connection);
  main.add(param);
  param.request_update();
};

add_param("A"s, function1);
add_param("B"s, function2);
add_param("C"s, function3);
}

**Comment by BenBE** [comment]
Shouldn't that labda take 2 arguments (`name` and `handler`)? Setting the `param.on_change=handler;` is missing in the cleaned-up example.

**Comment by xtofl** [comment]
yes - thanks.

**Comment by peno2** [comment]
I agree that the example with

    add_param("A"s, function1);
    add_param("B"s, function2);
    add_param("C"s, function3);

is a good rewrite. But I think it is a good idea to keep the code example as simple as possible.

The main reason to keep the example simple, is that the most important audience for this rule is inexperienced programmers.

Also, when the example could be kept simple and still illustrative enough, the rule can also be applied for code written in ordinary C. I know of programmers who are limited to programming in older versions of C++ or even C-89. I think it doesn't hurt if they could use as much as possible of the Core Guidlines. So here is my latest suggestion for an example, without any food-related references.

    void func(bool flag)    // Bad, duplicated code.
    {
        if (flag) {
            x();
            y();
        }
        else {
            x();
            z();
        }
    }

    void func(bool flag)    // Better, no duplicated code.
    {
        x();

        if (flag)
            y();
        else
            z();
    }

**Comment by hsutter** [comment]
Editors call: Merged, thanks!
